config/routes.rb
Rails.application.routes.draw do
  namespace :ag do
    resources :household_apartments
  end
  namespace :ag do
    resources :household_members
  end
  namespace :ag do
    resources :households
  end
  namespace :ag do
    resources :residents
  end
  namespace :ag do
    resources :apartments
  end
  namespace :ag do
    resources :states
  end
  namespace :ag do
    resources :countries
  end
  namespace :ag do
    resources :addresses
  end
  namespace :ag do
    resources :public_housing_devels
  end
  root to: 'visitors#index'
end

app/models/ag.rb
module Ag
  def self.table_name_prefix
    'ag_'
  end
end

app/models/ag/address.rb
class Ag::Address < ApplicationRecord
  has_one :ag_country
  has_one :ag_state

end

app/models/ag/apartment.rb
class Ag::Apartment < ApplicationRecord

  belongs_to :ag_public_housing_devel, class_name: 'Ag::PublicHousingDevel'
end

app/models/ag/country.rb
class Ag::Country < ApplicationRecord
  # belongs_to :ag_address, class_name: 'Ag::Address'
end

app/models/ag/household.rb
class Ag::Household < ApplicationRecord
end

app/models/ag/household_apartment.rb
class Ag::HouseholdApartment < ApplicationRecord
  belongs_to :ag_apartment, class_name: 'Ag::Apartment'
  belongs_to :ag_household, class_name: 'Ag::Household'

  belongs_to :ag_public_housing_devel, class_name: 'Ag::PublicHousingDevel'
end

app/models/ag/household_member.rb
class Ag::HouseholdMember < ApplicationRecord
  has_one :ag_household, class_name: 'Ag::Household'
  has_one :ag_resident, class_name: 'Ag::Resident'
  
end

app/models/ag/public_housing_devel.rb
class Ag::PublicHousingDevel < ApplicationRecord

  has_one :ag_address
end

app/models/ag/resident.rb
class Ag::Resident < ApplicationRecord
end

app/models/ag/state.rb
class Ag::State < ApplicationRecord
  belongs_to :ag_country, class_name: 'Ag::Country'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :show_flash

  private

  def show_flash
    #flash.now[:notice] = "Found the about page!" if request.path == '/pages/about'
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/ag/addresses_helper.rb
module Ag::AddressesHelper
end

app/helpers/ag/apartments_helper.rb
module Ag::ApartmentsHelper
end

app/helpers/ag/countries_helper.rb
module Ag::CountriesHelper
end

app/helpers/ag/households_helper.rb
module Ag::HouseholdsHelper
end

app/helpers/ag/residents_helper.rb
module Ag::ResidentsHelper
end

app/helpers/ag/states_helper.rb
module Ag::StatesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-dark bg-dark">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to "Public Housing Development Tracker", root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </nav>
</div>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link' %></li>
<li class='nav-item'><%= link_to 'Housing Projects', ag_public_housing_devels_path, class: 'nav-link' %></li>
<li class='nav-item'><%= link_to 'Apartments', ag_apartments_path, class: 'nav-link' %></li>
<li class='nav-item'><%= link_to 'Residents', ag_residents_path, class: 'nav-link' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Housing Development Project Tracker" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Online application to track the public housing development projects and their occupancy." %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <%= render 'layouts/navigation' %>
</header>
<main role="main">
  <%= render 'layouts/messages' %>
  <%= yield %>
</main>
</body>
</html>